title: Voeg een opening toe tussen omwikkelde elementen
hero_image: images/banner.png
description: Voeg een opening toe tussen omwikkelde elementen in een flexibele lay-out.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Voeg een opening toe tussen omwikkelde elementen

