title: Add a gap between wrapped elements
hero_image: images/banner.png
description: Add a gap between wrapped elements in a flex layout.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Add a gap between wrapped elements

