---
title: Ajouter un espace entre les éléments enveloppés
hero_image: images/banner.png
description: Ajoute un espace entre les éléments enveloppés dans une mise en page flex.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Ajouter un espace entre les éléments enveloppés

